### PR TITLE
Added zip & full content types, used by binaries.

### PR DESCRIPTION
**Pull request by alunmj**
Occasionally in my RCS, I'll see files (icons, images, etc) stored with special codes:
))[(###%%%~~~StoreCompleteRevision))[(###%%%~~~
))[(###%%%~~~StoreZippedRevision))[(###%%%~~~

This indicates that, along with file "blah,v", there's a folder "blah,v,f", with files for each revision, such as "1.0_1" or "1.0_2" - the "_1" is a complete revision, where this file is an exact copy of the file being stored. "_2" is a zipped revision, where the file is a zip file containing just the copy of the file in this revision.

I'll admit to sucking at Ruby, but I think the changes below are all that's required to support these two formats. This does require the presence of a "zip" tool, and more error checking would be nice to detect if "zip" isn't installed, or if the zip operation fails. I've also not added any error checking for "what if the file doesn't exist, or isn't in the place I've expected it". To be truly robust, you'd want that, but this is a quick submission by a non-Ruby author, so I'm leaving it to others to make it "proper Ruby".

If you find yourself asking "why did you write it this way, instead of that way", the answer will be "because I didn't know any better, and that's how it was written in the first sample I came across which worked".

I hoped "--expand-keywords" would have been sufficient, since it actually calls out to "co", but it doesn't seem that this works.

### CODE REVIEW

**Comment by Oblomov** [comment]
Thank you for the patch. Interestingly, this isn't standard RCS behavior, but looking a little bit around it seems to a perversion specific to CS-RCS from ComponentSoftware. I don't have a way to test the changes, but they look good. I assume a similar change should be also applied to the :diff switch case? Or are changes in binary files stored in the standard RCS format? If this is the case, then it's probably better to refactor the CS-specific checkout.

Also, I believe it should be done before checking for expand_keywords. Do you feel up to the task of updating the changeset? If not, I can give it a go, but I cannot guarantee that the resulting refactor will still  work, since I don't have a repository to test this on. (If you know of a test CS-RCS repository with committed changes to binary files, I'd be glad.)

**Comment by alunmj** [comment]
Thanks for the quick response - I figured since there was so much time since the last checkin, nobody was paying attention.
You're right that I'm working against CS-RCS, and I'll have a look at the :diff switch - it looks like the text for the older version reads "@@", when two versions are both stored as zipped or complete files. I have relatively few such files in my repositories, and didn't feel the need to go check their history so much. I also notice I have one edge case where the file is stored in one revision as a zip file, and in an earlier revision as inline diffs, which is going to be an interesting one to resolve.
Now that I know there's someone actually monitoring the changes to this Ruby script, I'll be happy to accommodate changes and submit a more complete and thorough change. I can't promise when I can work on it, though. I shall probably also create a quick test repository to work against.

**Comment by Oblomov** [comment]
> Thanks for the quick response - I figured since there was so much time since the last checkin, nobody was paying attention.

As I don't use the tool myself anymore, stuff only happens when someone comes across a specific issue, such as the one you came across with CS-RCS. (The list of TODOs is more of a wishlist for stuff to twiddle about if/when I —or anybody else— has the time.)

> You're right that I'm working against CS-RCS, and I'll have a look at the :diff switch - it looks like the text for the older version reads "@@", when two versions are both stored as zipped or complete files

Interesting. The real question in this case is then if the binary storage for subsequent revisions is the actual binary content (compressed or uncompressed), or some form of binary diff.

> I have relatively few such files in my repositories, and didn't feel the need to go check their history so much. I also notice I have one edge case where the file is stored in one revision as a zip file, and in an earlier revision as inline diffs, which is going to be an interesting one to resolve.

And there's also the possibility for the other way around too (older revision binary, more recent revision text). If the binary storage system always stores the complete content, handling both the binary-to-text and the text-to-binary switch should be relatively painless, by simply using the 'decode binary' codepath for binary revisions, and the 'decode text' codepath (the classic RCS stuff already in rcs-fast-export, basically) for text revisions: as the diffs are computed from the previous version of the file, it should work out smoothly, using the same approach you already coded for the :text branch. (BTW in the zip case you have two assignments to myZipLines, you probably want to keep only the second one, the one usign IO.binread.)

>  Now that I know there's someone actually monitoring the changes to this Ruby script, I'll be happy to accommodate changes and submit a more complete and thorough change. I can't promise when I can work on it, though. I shall probably also create a quick test repository to work against.

Take your time. If you need some kind of help with the Ruby-specific part, feel free to ask. I can hack up some of the code myself. If you can cook up even just a small repository for test, with a few of the corner cases in (binary with two revisions, a file that went from binary to text, one that went from text to binary, and maybe something that ping-ponged), it'd be potentially even more useful, as then I can just merge your current patch and then iron out the other details.

**Comment by alunmj** [comment]
I think this looks better now. I also attached a zip of a CS-RCS repository that I created to demonstrate the different binary types - full for png, zipped for ico.

**Comment by Oblomov** [comment]
Thanks for the patch. I will try and give it a spin as soon as I have the time (hopefully by the end of the week).

**Pull request closed without merging**
